# Generated by Django 4.1.7 on 2023-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EleventhClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('CBSE_STATE', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('JOIN_DATE', models.CharField(max_length=100)),
                ('SUBJECT', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=100)),
                ('PRICE', models.CharField(max_length=100)),
                ('DISCOUNT', models.CharField(max_length=100)),
                ('TOTAL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NinthClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('CBSE_STATE', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('JOIN_DATE', models.CharField(max_length=100)),
                ('SUBJECT', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=100)),
                ('PRICE', models.CharField(max_length=100)),
                ('DISCOUNT', models.CharField(max_length=100)),
                ('TOTAL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TenthClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('CBSE_STATE', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('JOIN_DATE', models.CharField(max_length=100)),
                ('SUBJECT', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=100)),
                ('PRICE', models.CharField(max_length=100)),
                ('DISCOUNT', models.CharField(max_length=100)),
                ('TOTAL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TwelvethClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('CBSE_STATE', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('JOIN_DATE', models.CharField(max_length=100)),
                ('SUBJECT', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=100)),
                ('PRICE', models.CharField(max_length=100)),
                ('DISCOUNT', models.CharField(max_length=100)),
                ('TOTAL', models.CharField(max_length=100)),
            ],
        ),
    ]
