# Generated by Django 4.1.7 on 2023-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleventhAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NinthAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TenthAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TwelvethAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('STUDENT_ID', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ixpayment',
            name='SUBJECT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xiipayment',
            name='SUBJECT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xipayment',
            name='SUBJECT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xpayment',
            name='SUBJECT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
