# Generated by Django 4.1.7 on 2023-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_ixpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='XIIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('PAYMENT_RECEIPT_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('DATE_OF_PAYMENT', models.CharField(max_length=100)),
                ('NET_AMOUNT_PAID', models.CharField(max_length=100)),
                ('MODE_OF_PAYMENT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('PAYMENT_RECEIPT_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('DATE_OF_PAYMENT', models.CharField(max_length=100)),
                ('NET_AMOUNT_PAID', models.CharField(max_length=100)),
                ('MODE_OF_PAYMENT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('PAYMENT_RECEIPT_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('CLASS', models.CharField(max_length=100)),
                ('DATE_OF_PAYMENT', models.CharField(max_length=100)),
                ('NET_AMOUNT_PAID', models.CharField(max_length=100)),
                ('MODE_OF_PAYMENT', models.CharField(max_length=100)),
            ],
        ),
    ]
