# Generated by Django 4.1.7 on 2023-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_xiipayment_xipayment_xpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('ATTENDANCE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('ATTENDANCE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XIAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('ATTENDANCE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XIIAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_ID', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('ATTENDANCE', models.CharField(max_length=100)),
            ],
        ),
    ]
